const tamanhosSandalia = [33, 34, 35, 36, 37, 38, 39, 40];

export const oleos = [
  {
    id: 1,
    slug: 'oleo-bergamota',
    nome: 'Bergamot - Óleo Essencial',
    categoria: 'Óleo Essencial',
    subtitulo: 'Aroma cítrico e refrescante, ideal para equilíbrio emocional e bem-estar.',
    descricao: 'A Bergamota doTERRA é extraída da casca da fruta Citrus bergamia. Com aroma cítrico e floral único, é amplamente usada em aromaterapia para promover relaxamento, bem-estar emocional e equilíbrio mental.',
    preco: 'R$ 310,00',
    parcelamento: '3x de R$ 103,33 sem juros',
    tamanho: '15 ml',
    img: '/fotos/oleos/aromas_naturais/bergamot.png',
    beneficios: ['Reduz ansiedade e estresse', 'Promove sensação de calma e alegria', 'Purifica e limpa a pele', 'Ideal para aromaterapia e difusores', 'Equilibra as emoções e eleva o humor'],
    tags: ['Calmante', 'Aromaterapia', 'doTERRA', 'Cítrico'],
    comoUsar: [
      { icon: '💨', titulo: 'Difusor', desc: '3–4 gotas no difusor para ambientar qualquer espaço.' },
      { icon: '🖐️', titulo: 'Tópico', desc: 'Dilua com óleo carreador e aplique na pele.' },
      { icon: '🛁', titulo: 'Banho', desc: 'Adicione gotas no banho para relaxamento profundo.' },
      { icon: '🌿', titulo: 'Inalação', desc: 'Respire diretamente do frasco para alívio imediato.' },
    ],
  },
  {
    id: 2,
    slug: 'oleo-pimenta-preta',
    nome: 'Black Pepper - Óleo Essencial',
    categoria: 'Óleo Essencial',
    subtitulo: 'Estimulante e aquecedor, perfeito para circulação e desconforto muscular.',
    descricao: 'O Óleo Essencial de Pimenta Preta doTERRA é extraído das sementes imaturas da Piper nigrum. Com aroma picante, quente e levemente amadeirado, é reconhecido por suas propriedades estimulantes e antioxidantes.',
    preco: 'R$ 250,00',
    parcelamento: '3x de R$ 83,33 sem juros',
    tamanho: '5 ml',
    img: '/fotos/oleos/aromas_naturais/black_pepper.png',
    beneficios: ['Estimula a circulação sanguínea', 'Alivia tensão e desconforto muscular', 'Apoia a digestão saudável', 'Rico em antioxidantes naturais', 'Aroma quente e revigorante'],
    tags: ['Circulação', 'Antioxidante', 'doTERRA', 'Estimulante'],
    comoUsar: [
      { icon: '💨', titulo: 'Difusor', desc: '2–3 gotas para um ambiente aquecedor e energizante.' },
      { icon: '🖐️', titulo: 'Massagem', desc: 'Dilua e massageie em áreas de tensão muscular.' },
      { icon: '🍽️', titulo: 'Culinário', desc: '1 gota em receitas para sabor e digestão.' },
      { icon: '🌿', titulo: 'Inalação', desc: 'Inalação direta para foco e energia.' },
    ],
  },
  {
    id: 3,
    slug: 'oleo-basil',
    nome: 'Basil - Óleo Essencial',
    categoria: 'Óleo Essencial',
    subtitulo: 'Herbal e refrescante, excelente para clareza mental e relaxamento.',
    descricao: 'O Óleo Essencial de Manjericão doTERRA é extraído das folhas da planta Ocimum basilicum. Com aroma herbal, fresco e levemente adocicado, é amplamente utilizado para clareza mental, relaxamento e suporte digestivo.',
    preco: 'R$ 307,00',
    parcelamento: '3x de R$ 102,33 sem juros',
    tamanho: '15 ml',
    img: '/fotos/oleos/aromas_naturais/brasil.png',
    beneficios: ['Promove clareza mental e foco', 'Reduz fadiga e estresse mental', 'Apoia a digestão saudável', 'Aroma herbal fresco e revitalizante', 'Ideal para difusor e uso tópico diluído'],
    tags: ['Clareza Mental', 'Herbal', 'doTERRA', 'Relaxante'],
    comoUsar: [
      { icon: '💨', titulo: 'Difusor', desc: '3–4 gotas no difusor para clareza e foco.' },
      { icon: '🧘', titulo: 'Meditação', desc: 'Use durante práticas de meditação e yoga.' },
      { icon: '🖐️', titulo: 'Tópico', desc: 'Dilua e aplique nas têmporas para foco mental.' },
      { icon: '🌿', titulo: 'Inalação', desc: 'Inalação direta para alívio imediato de fadiga.' },
    ],
  },
  {
    id: 4,
    slug: 'oleo-cardamomo',
    nome: 'Cardamomo - Óleo Essencial',
    categoria: 'Óleo Essencial',
    subtitulo: 'Doce e especiado, excelente para digestão e respiração saudável.',
    descricao: 'O Cardamomo doTERRA tem aroma quente, especiado e levemente adocicado. Extraído das sementes da planta Elettaria cardamomum, é amplamente utilizado para suporte digestivo e revitalização.',
    preco: 'R$ 272,00',
    parcelamento: '3x de R$ 90,67 sem juros',
    tamanho: '5 ml',
    img: '/fotos/oleos/aromas_naturais/cardamom.png',
    beneficios: ['Apoia a saúde digestiva e o metabolismo', 'Promove respiração limpa e fácil', 'Aroma doce, quente e especiado', 'Propriedades anti-inflamatórias naturais', 'Estimula a vitalidade e a energia'],
    tags: ['Digestivo', 'Especiado', 'doTERRA', 'Vitalizante'],
    comoUsar: [
      { icon: '💨', titulo: 'Difusor', desc: '3 gotas para um aroma quente e acolhedor.' },
      { icon: '🍽️', titulo: 'Culinário', desc: '1 gota em chás, cafés e sobremesas.' },
      { icon: '🖐️', titulo: 'Tópico', desc: 'Aplique diluído no abdômen para suporte digestivo.' },
      { icon: '🌿', titulo: 'Inalação', desc: 'Inalação direta para clareza respiratória.' },
    ],
  },
  {
    id: 5,
    slug: 'oleo-cassia',
    nome: 'Cassia - Óleo Essencial',
    categoria: 'Óleo Essencial',
    subtitulo: 'Similar à canela, com propriedades quentes e estimulantes do bem-estar.',
    descricao: 'A Cassia doTERRA tem um aroma quente, adocicado e especiado, semelhante à canela. Extraída da casca da Cinnamomum cassia, é conhecida por suas propriedades aquecedoras e de suporte ao sistema imunológico.',
    preco: 'R$ 200,00',
    parcelamento: '3x de R$ 66,67 sem juros',
    tamanho: '15 ml',
    img: '/fotos/oleos/aromas_naturais/cassia.png',
    beneficios: ['Fortalece e apoia o sistema imunológico', 'Aroma quente e reconfortante, semelhante à canela', 'Estimula a circulação e a vitalidade', 'Promove sensação de aquecimento', 'Excelente para uso em difusor'],
    tags: ['Imunidade', 'Aquecedor', 'doTERRA', 'Canela'],
    comoUsar: [
      { icon: '💨', titulo: 'Difusor', desc: '2 gotas para um ambiente aconchegante no inverno.' },
      { icon: '🍽️', titulo: 'Culinário', desc: '1 gota em receitas que pedem canela.' },
      { icon: '🖐️', titulo: 'Tópico', desc: 'Dilua bastante antes de aplicar na pele.' },
      { icon: '🛁', titulo: 'Banho', desc: '2 gotas no banho para aquecimento corporal.' },
    ],
  },
  {
    id: 24,
    slug: 'oleo-adaptiv',
    nome: 'Adaptiv Mix Calmante',
    categoria: 'Mix de Óleos Essenciais',
    subtitulo: 'Mix calmante para suporte ao bem-estar emocional e redução do estresse.',
    descricao: 'O Adaptiv doTERRA é um mix de óleos essenciais formulado para trazer calma e conforto em momentos de estresse e ansiedade. Combina óleos com propriedades calmantes para equilibrar as emoções e promover tranquilidade.',
    preco: 'R$ 378,00',
    parcelamento: '3x de R$ 126,00 sem juros',
    tamanho: '15 ml',
    img: '/fotos/oleos/mix_oleo_essencial/adaptiv.png',
    beneficios: ['Promove sensação de calma e tranquilidade', 'Reduz o estresse e a ansiedade', 'Apoia o bem-estar emocional', 'Aroma equilibrante e relaxante', 'Ideal para momentos de tensão e pressão'],
    tags: ['Calmante', 'Estresse', 'doTERRA', 'Mix Essencial'],
    comoUsar: [
      { icon: '💨', titulo: 'Difusor', desc: '4 gotas no difusor para criar um ambiente de calma.' },
      { icon: '🖐️', titulo: 'Tópico', desc: 'Dilua e aplique no pescoço e pulsos para alívio.' },
      { icon: '🧘', titulo: 'Meditação', desc: 'Use durante práticas de meditação e respiração.' },
      { icon: '🌿', titulo: 'Inalação', desc: 'Respire diretamente para alívio imediato do estresse.' },
    ],
  },
  {
    id: 25,
    slug: 'oleo-adaptiv-touch',
    nome: 'Adaptiv Touch Mix Calmante',
    categoria: 'Mix de Óleos Essenciais',
    subtitulo: 'Versão roll-on do Mix Calmante, prática para aplicação tópica a qualquer hora.',
    descricao: 'O Adaptiv Touch doTERRA traz a fórmula calmante do Adaptiv® em formato roll-on prático. Pré-diluído em óleo carreador, facilita a aplicação tópica direta nos pulsos, pescoço e têmporas sempre que precisar.',
    preco: 'R$ 200,00',
    parcelamento: '3x de R$ 66,67 sem juros',
    tamanho: '10 ml',
    img: '/fotos/oleos/mix_oleo_essencial/adaptiv_touch.png',
    beneficios: ['Formato roll-on para aplicação prática e rápida', 'Pré-diluído pronto para uso tópico', 'Promove calma e bem-estar emocional', 'Ideal para levar na bolsa no dia a dia', 'Alivia o estresse onde e quando precisar'],
    tags: ['Calmante', 'Roll-on', 'doTERRA', 'Prático'],
    comoUsar: [
      { icon: '🖐️', titulo: 'Pulsos', desc: 'Aplique nos pulsos e esfregue suavemente.' },
      { icon: '🌿', titulo: 'Pescoço', desc: 'Passe no pescoço para relaxamento rápido.' },
      { icon: '😌', titulo: 'Têmporas', desc: 'Aplique nas têmporas para alívio de tensão.' },
      { icon: '👃', titulo: 'Inalação', desc: 'Após aplicar, respire fundo para potencializar o efeito.' },
    ],
  },
  {
    id: 26,
    slug: 'oleo-air-x',
    nome: 'Air-X Mix de Óleos Essenciais',
    categoria: 'Mix de Óleos Essenciais',
    subtitulo: 'Mix respiratório que apoia a saúde das vias aéreas e o conforto respiratório.',
    descricao: 'O Air-X® doTERRA é um mix de óleos essenciais desenvolvido para oferecer suporte às vias respiratórias. Combina óleos com propriedades que facilitam a respiração limpa, confortável e revigorante.',
    preco: 'R$ 232,00',
    parcelamento: '3x de R$ 77,33 sem juros',
    tamanho: '15 ml',
    img: '/fotos/oleos/mix_oleo_essencial/air_x.png',
    beneficios: ['Apoia a saúde das vias respiratórias', 'Promove respiração limpa e confortável', 'Alivia desconfortos respiratórios sazonais', 'Aroma fresco e revigorante', 'Ideal para difusor durante estações de alergias'],
    tags: ['Respiratório', 'Vias Aéreas', 'doTERRA', 'Mix Essencial'],
    comoUsar: [
      { icon: '💨', titulo: 'Difusor', desc: '3–4 gotas no difusor para purificar o ambiente.' },
      { icon: '🖐️', titulo: 'Tópico', desc: 'Dilua e aplique no peito e costas para suporte respiratório.' },
      { icon: '🌿', titulo: 'Inalação', desc: 'Inalação direta para alívio respiratório imediato.' },
      { icon: '🛁', titulo: 'Banho a Vapor', desc: 'Adicione gotas na água quente do banho e respire o vapor.' },
    ],
  },
];

export const purificadores = [
  {
    id: 8,
    slug: 'purificador-azul-um-filtro',
    nome: 'Purificador de Água Natural Azul',
    categoria: 'Purificador de Água',
    subtitulo: 'Purificador compacto com 1 filtro, ideal para uso doméstico diário.',
    descricao: 'O Purificador Purific Azul é compacto e elegante, com um filtro de alta eficiência que remove impurezas, cloro e sedimentos. Ideal para famílias que buscam água limpa com design moderno e instalação simples.',
    preco: 'R$ 349,90',
    parcelamento: '12x de R$ 29,16 sem juros',
    img: '/fotos/purificador/purificador_agua_natural/purificador3.png',
    beneficios: ['Remove cloro, sedimentos e impurezas', 'Design compacto e moderno na cor azul', 'Instalação simples sem necessidade de técnico', 'Filtro de longa duração e fácil reposição', 'Certificado pela ANVISA'],
    tags: ['Purificação', 'Compacto', 'Azul', 'Família'],
    specs: [
      { label: 'Número de filtros', valor: '1' },
      { label: 'Cor', valor: 'Azul' },
      { label: 'Capacidade', valor: 'Fluxo contínuo' },
      { label: 'Instalação', valor: 'Sem obra' },
      { label: 'Garantia', valor: '12 meses' },
    ],
    diferenciais: [
      { icon: '💧', titulo: 'Água Pura', desc: 'Remove impurezas, cloro e odores indesejados.' },
      { icon: '🔧', titulo: 'Fácil Instalação', desc: 'Conecta diretamente à torneira, sem obra.' },
      { icon: '💰', titulo: 'Econômico', desc: 'Custo por litro muito menor que água engarrafada.' },
      { icon: '🌱', titulo: 'Sustentável', desc: 'Reduz o uso de plástico descartável.' },
    ],
  },
  {
    id: 9,
    slug: 'purificador-preto-dois-filtros',
    nome: 'Purificador de Água Natural Preto',
    categoria: 'Purificador de Água',
    subtitulo: 'Máxima purificação com duplo filtro para famílias que exigem mais qualidade.',
    descricao: 'O Purificador Purific Preto conta com dois filtros de purificação para máxima eficiência. Remove cloro, metais pesados, bactérias e impurezas em dupla etapa. Design sofisticado na cor preta.',
    preco: 'R$ 499,90',
    parcelamento: '12x de R$ 41,66 sem juros',
    img: '/fotos/purificador/purificador_bebedouro/purificador4.png',
    beneficios: ['Dupla filtração para máxima pureza', 'Remove cloro, metais pesados e bactérias', 'Design sofisticado na cor preta', 'Maior capacidade de filtragem', 'Certificado pela ANVISA'],
    tags: ['Duplo Filtro', 'Preto', 'Premium', 'Alta Eficiência'],
    specs: [
      { label: 'Número de filtros', valor: '2' },
      { label: 'Cor', valor: 'Preto' },
      { label: 'Capacidade', valor: 'Fluxo contínuo' },
      { label: 'Instalação', valor: 'Sem obra' },
      { label: 'Garantia', valor: '12 meses' },
    ],
    diferenciais: [
      { icon: '💧', titulo: 'Dupla Filtração', desc: 'Dois estágios de filtragem para água ainda mais pura.' },
      { icon: '🏆', titulo: 'Premium', desc: 'Design sofisticado que combina com qualquer cozinha.' },
      { icon: '👨‍👩‍👧‍👦', titulo: 'Para Famílias', desc: 'Maior capacidade para o consumo de toda a família.' },
      { icon: '🌱', titulo: 'Sustentável', desc: 'Elimine as garrafas plásticas da sua rotina.' },
    ],
  },
  {
    id: 10,
    slug: 'purificador-branco-dois-filtros',
    nome: 'Purificador de Água Natural Branco',
    categoria: 'Purificador de Água',
    subtitulo: 'Elegância em branco com duplo filtro para uma purificação superior.',
    descricao: 'O Purificador Purific Branco com dois filtros oferece purificação em dupla etapa com visual clean e sofisticado. Combina alta performance de filtragem com um design neutro que se adapta a qualquer ambiente.',
    preco: 'R$ 479,90',
    parcelamento: '12x de R$ 39,99 sem juros',
    img: '/fotos/purificador/purificador_agua_natural/purificador5.png',
    beneficios: ['Dupla filtração para água mais pura', 'Design clean e neutro na cor branca', 'Fácil manutenção e troca de filtros', 'Remove impurezas, cloro e metais pesados', 'Certificado pela ANVISA'],
    tags: ['Duplo Filtro', 'Branco', 'Clean', 'Alta Eficiência'],
    specs: [
      { label: 'Número de filtros', valor: '2' },
      { label: 'Cor', valor: 'Branco' },
      { label: 'Capacidade', valor: 'Fluxo contínuo' },
      { label: 'Instalação', valor: 'Sem obra' },
      { label: 'Garantia', valor: '12 meses' },
    ],
    diferenciais: [
      { icon: '💧', titulo: 'Dupla Filtração', desc: 'Dois estágios para água pura e segura.' },
      { icon: '✨', titulo: 'Design Clean', desc: 'Branco elegante que valoriza sua cozinha.' },
      { icon: '👨‍👩‍👧‍👦', titulo: 'Para Famílias', desc: 'Ideal para famílias de médio e grande porte.' },
      { icon: '🌱', titulo: 'Eco-friendly', desc: 'Contribua com o meio ambiente reduzindo plástico.' },
    ],
  },
  {
    id: 11,
    slug: 'purificador-preto-um-filtro',
    nome: 'Purificador Purific Preto Compacto',
    categoria: 'Purificador de Água',
    subtitulo: 'Compacto e eficiente com design preto moderno para sua torneira.',
    descricao: 'Versão compacta do Purificador Purific na cor preta, com um filtro eficiente para purificação do dia a dia. Perfeito para espaços menores sem abrir mão da qualidade e do estilo.',
    preco: 'R$ 329,90',
    parcelamento: '12x de R$ 27,49 sem juros',
    img: '/fotos/purificador/purificador_agua_natural/purificador4.png',
    beneficios: ['Compacto e perfeito para espaços menores', 'Remove cloro, sedimentos e impurezas', 'Design elegante na cor preta', 'Fácil instalação e manutenção', 'Certificado pela ANVISA'],
    tags: ['Compacto', 'Preto', 'Purificação', 'Prático'],
    specs: [
      { label: 'Número de filtros', valor: '1' },
      { label: 'Cor', valor: 'Preto' },
      { label: 'Capacidade', valor: 'Fluxo contínuo' },
      { label: 'Instalação', valor: 'Sem obra' },
      { label: 'Garantia', valor: '12 meses' },
    ],
    diferenciais: [
      { icon: '💧', titulo: 'Água Pura', desc: 'Filtro de alta performance para sua saúde.' },
      { icon: '🎨', titulo: 'Design Moderno', desc: 'Visual preto minimalista e contemporâneo.' },
      { icon: '💰', titulo: 'Econômico', desc: 'Investimento acessível com retorno rápido.' },
      { icon: '🌱', titulo: 'Sustentável', desc: 'Menos plástico, mais consciência ambiental.' },
    ],
  },
  {
    id: 12,
    slug: 'purificador-branco-um-filtro',
    nome: 'Purificador Purific Branco Compacto',
    categoria: 'Purificador de Água',
    subtitulo: 'Clássico e eficiente, ideal para quem busca praticidade no dia a dia.',
    descricao: 'O Purificador Purific Branco Compacto é a escolha ideal para quem busca praticidade e qualidade. Com design minimalista e filtro de alta eficiência, entrega água pura e saborosa no dia a dia.',
    preco: 'R$ 299,90',
    parcelamento: '12x de R$ 24,99 sem juros',
    img: '/fotos/purificador/purificador_agua_natural/purificador2.png',
    beneficios: ['Design minimalista e versátil', 'Remove cloro, sedimentos e impurezas', 'Ideal para cozinhas de qualquer tamanho', 'Fácil instalação e manutenção', 'Certificado pela ANVISA'],
    tags: ['Compacto', 'Branco', 'Minimalista', 'Prático'],
    specs: [
      { label: 'Número de filtros', valor: '1' },
      { label: 'Cor', valor: 'Branco' },
      { label: 'Capacidade', valor: 'Fluxo contínuo' },
      { label: 'Instalação', valor: 'Sem obra' },
      { label: 'Garantia', valor: '12 meses' },
    ],
    diferenciais: [
      { icon: '💧', titulo: 'Água Limpa', desc: 'Remoção eficiente de cloro, metais e odores.' },
      { icon: '✨', titulo: 'Visual Clean', desc: 'Design branco que se adapta a qualquer ambiente.' },
      { icon: '⚡', titulo: 'Fácil Uso', desc: 'Operação simples e manutenção descomplicada.' },
      { icon: '🌱', titulo: 'Sustentável', desc: 'Contribua com o planeta reduzindo resíduos plásticos.' },
    ],
  },
];

export const sandalias = [
  {
    id: 13,
    slug: 'sandalia-ortopedica-couro',
    nome: 'Sandalia Ortopedica Couro',
    categoria: 'Sandalia Ortopedica',
    descricao: 'Confeccionada em couro legitimo com palmilha anatomica para suporte total do arco plantar. Indicada para uso diario, corrige a postura e alivia dores nos pes, joelhos e coluna.',
    preco: 'R$ 189,90',
    parcelamento: '6x de R$ 31,65 sem juros',
    img: '/fotos/sandalias/sandalia_couro.jpg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Couro legitimo de alta durabilidade', 'Palmilha anatomica para suporte do arco plantar', 'Corrige a postura e alivia dores', 'Indicada para uso diario', 'Unissex - disponivel nos tamanhos 33 ao 40'],
    tags: ['Couro Legitimo', 'Arco Plantar', 'Unissex', 'Ortopedica'],
  },
  {
    id: 14,
    slug: 'sandalia-ortopedica-vazada',
    nome: 'Sandalia Ortopedica Vazada',
    categoria: 'Sandalia Ortopedica',
    descricao: 'Design vazado com solado ortopedico para maxima ventilacao e conforto. Leve e resistente, ideal para quem passa longos periodos em pe e busca frescor sem abrir mao do suporte postural.',
    preco: 'R$ 159,90',
    parcelamento: '6x de R$ 26,65 sem juros',
    img: '/fotos/sandalias/sandaliavazada.jpeg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Design vazado para maxima ventilacao', 'Solado ortopedico com amortecimento', 'Extremamente leve e confortavel', 'Ideal para dias quentes e rotinas longas', 'Disponivel nos tamanhos 33 ao 40'],
    tags: ['Ventilada', 'Leve', 'Feminino', 'Ortopedica'],
  },
  {
    id: 15,
    slug: 'sandalia-ortopedica-premium',
    nome: 'Sandalia Ortopedica Premium',
    categoria: 'Sandalia Ortopedica',
    descricao: 'A linha Premium combina amortecimento extra com correcao postural avancada. Material nobre, acabamento impecavel e tecnologia ortopedica de alto nivel para quem exige o melhor para a saude dos pes.',
    preco: 'R$ 219,90',
    parcelamento: '6x de R$ 36,65 sem juros',
    img: '/fotos/sandalias/sandalia_couro.jpg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Amortecimento extra para maximo conforto', 'Correcao postural avancada', 'Material nobre com acabamento premium', 'Reduz dores nos pes, joelhos e coluna', 'Disponivel nos tamanhos 33 ao 40'],
    tags: ['Premium', 'Amortecimento', 'Postura', 'Ortopedica'],
  },
  {
    id: 16,
    slug: 'sandalia-magnetica-classic',
    nome: 'Sandalia Magnetica Classic',
    categoria: 'Sandalia Magnetica',
    descricao: 'Imaes terapeuticos estrategicamente posicionados para estimular a circulacao sanguinea e aliviar dores. A linha Classic e a introducao perfeita a tecnologia magnetica com estilo elegante e moderno.',
    preco: 'R$ 229,90',
    parcelamento: '6x de R$ 38,32 sem juros',
    img: '/fotos/sandalias/sandaliavazada.jpeg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Imaes terapeuticos para estimular a circulacao', 'Alivia dores e reduz inflamacoes', 'Estilo elegante para uso no dia a dia', 'Promove equilibrio energetico', 'Disponivel nos tamanhos 33 ao 40'],
    tags: ['Circulacao', 'Terapeutica', 'Unissex', 'Magnetica'],
  },
  {
    id: 17,
    slug: 'sandalia-magnetica-bio',
    nome: 'Sandalia Magnetica Bio',
    categoria: 'Sandalia Magnetica',
    descricao: 'Combina tecnologia magnetica com materiais bioativos para bem-estar total. Os materiais bioativos potencializam a acao dos imaes, promovendo recuperacao muscular, equilibrio e vitalidade ao longo do dia.',
    preco: 'R$ 249,90',
    parcelamento: '6x de R$ 41,65 sem juros',
    img: '/fotos/sandalias/sandalia_couro.jpg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Materiais bioativos que potencializam os imaes', 'Promove recuperacao muscular acelerada', 'Estimula o equilibrio energetico', 'Alta tecnologia para bem-estar total', 'Disponivel nos tamanhos 33 ao 40'],
    tags: ['Bioativo', 'Alta Tecnologia', 'Feminino', 'Magnetica'],
  },
  {
    id: 18,
    slug: 'sandalia-magnetica-sport',
    nome: 'Sandalia Magnetica Sport',
    categoria: 'Sandalia Magnetica',
    descricao: 'Para quem tem rotina ativa. Magnetos de alta intensidade combinados com solado antiderrapante e estrutura reforcada para suportar os desafios do dia a dia com conforto e seguranca.',
    preco: 'R$ 269,90',
    parcelamento: '6x de R$ 44,98 sem juros',
    img: '/fotos/sandalias/sandalia_couro.jpg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Magnetos de alta intensidade para maximo efeito', 'Solado antiderrapante para maior seguranca', 'Estrutura reforcada para rotinas ativas', 'Ideal para quem pratica atividades fisicas', 'Disponivel nos tamanhos 33 ao 40'],
    tags: ['Esportivo', 'Antiderrapante', 'Unissex', 'Magnetica'],
  },
];

export const outrosProdutos = [
  {
    id: 6,
    slug: 'filtro-purific',
    nome: 'Filtro de Agua Purific',
    categoria: 'Purificador de Agua',
    descricao: 'O Filtro Purific oferece purificacao avancada em multiplos estagios, eliminando impurezas, cloro, metais pesados e microrganismos. Design moderno e compacto, facil instalacao e baixa manutencao.',
    preco: 'R$ 349,90',
    parcelamento: '12x de R$ 29,16 sem juros',
    img: '/fotos/purificador/filtro_de_agua.jpg',
    beneficios: ['Purificacao avancada em multiplos estagios', 'Remove cloro, metais pesados e microrganismos', 'Design moderno e compacto', 'Facil instalacao sem necessidade de tecnico', 'Baixa manutencao e alta durabilidade', 'Certificado pela ANVISA'],
    tags: ['Saude', 'Purificacao', 'Familia', 'Economico'],
  },
  {
    id: 7,
    slug: 'kit-bem-estar-doterra',
    nome: 'Kit Bem-Estar doTERRA',
    categoria: 'Kit Essencial',
    descricao: 'O Kit Bem-Estar doTERRA reune os oleos essenciais mais populares da marca em um conjunto completo para transformar sua rotina. Ideal para iniciantes e para quem deseja ter sempre a mao as melhores solucoes naturais.',
    preco: 'R$ 389,90',
    parcelamento: '12x de R$ 32,49 sem juros',
    img: '/fotos/oleos/doTERRA_Essencial_Para_o_Lar.png',
    beneficios: ['Kit completo com os oleos essenciais mais populares', 'Ideal para iniciantes em aromaterapia', 'Solucoes naturais para saude e bem-estar diario', 'Oleos 100% puros e certificados doTERRA', 'Guia de uso incluido no kit', 'Embalagem premium - otima opcao de presente'],
    tags: ['Kit Completo', 'doTERRA', 'Presente', 'Bem-Estar'],
  },
];

export const sandaliasCarrossel = [
  {
    id: 19,
    slug: 'sandalia-aurora-plataforma',
    nome: 'Sandália Ortopédica Couro Aurora',
    categoria: 'Sandália Ortopédica',
    descricao: 'Feita em couro legítimo com plataforma elevada e palmilha anatômica, a Aurora une estilo e suporte ortopédico. Ideal para quem busca conforto durante longas caminhadas sem abrir mão de um visual elegante.',
    preco: 'R$ 199,90',
    parcelamento: '6x de R$ 33,32 sem juros',
    img: '/fotos/sandalias/sandalia1.jpg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Couro legítimo de alta qualidade', 'Plataforma que alivia pressão no calcanhar', 'Palmilha anatômica com suporte total', 'Design elegante para uso diário e social', 'Disponível nos tamanhos 33 ao 40'],
    tags: ['Couro Legítimo', 'Plataforma', 'Unissex', 'Ortopédica'],
  },
  {
    id: 20,
    slug: 'sandalia-marron-salto-curto',
    nome: 'Sandália Ortopédica Marron Salto Curto',
    categoria: 'Sandália Ortopédica',
    descricao: 'Com salto curto e estrutura ortopédica, esta sandália na cor marrom combina praticidade e sofisticação. A palmilha com suporte do arco plantar reduz a fadiga e corrige a postura ao longo do dia.',
    preco: 'R$ 179,90',
    parcelamento: '6x de R$ 29,98 sem juros',
    img: '/fotos/sandalias/sandalia3.jpeg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Salto curto de 4 cm para postura ideal', 'Palmilha com suporte de arco plantar', 'Material resistente e de fácil higienização', 'Cor marrom versátil para qualquer look', 'Disponível nos tamanhos 33 ao 40'],
    tags: ['Salto Curto', 'Marrom', 'Feminino', 'Ortopédica'],
  },
  {
    id: 21,
    slug: 'sandalia-confort-couro-legitimo',
    nome: 'Sandália Confort Couro Legítimo',
    categoria: 'Sandália Ortopédica',
    descricao: 'A Confort Couro Legítimo é confeccionada com couro premium e palmilha extra macia para absorção de impacto. Perfeita para o dia a dia de quem exige conforto máximo sem comprometer a elegância.',
    preco: 'R$ 189,90',
    parcelamento: '6x de R$ 31,65 sem juros',
    img: '/fotos/sandalias/sandalia7.jpeg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Couro legítimo premium com acabamento fino', 'Palmilha extra macia para absorção de impacto', 'Solado antiderrapante para maior segurança', 'Conforto prolongado para uso diário', 'Disponível nos tamanhos 33 ao 40'],
    tags: ['Couro Premium', 'Extra Macia', 'Unissex', 'Confort'],
  },
  {
    id: 22,
    slug: 'sandalia-confort-plus',
    nome: 'Sandália Confort Plus',
    categoria: 'Sandália Ortopédica',
    descricao: 'A linha Confort Plus oferece amortecimento superior com tecnologia de gel na palmilha. Indicada para pessoas que passam muitas horas em pé, proporciona alívio imediato de dores e suporte contínuo.',
    preco: 'R$ 169,90',
    parcelamento: '6x de R$ 28,32 sem juros',
    img: '/fotos/sandalias/sandalia2.jpg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Tecnologia de gel na palmilha para amortecimento extra', 'Reduz dores nos pés e joelhos', 'Leve e resistente para uso prolongado', 'Design moderno e confortável', 'Disponível nos tamanhos 33 ao 40'],
    tags: ['Gel', 'Amortecimento', 'Feminino', 'Confort Plus'],
  },
  {
    id: 23,
    slug: 'sandalia-confort-estilo',
    nome: 'Sandália Confort Com Estilo',
    categoria: 'Sandália Ortopédica',
    descricao: 'União perfeita entre moda e ortopedia. A Confort Com Estilo traz design arrojado com tecnologia ortopédica avançada para quem não abre mão de estar na moda sem sacrificar a saúde dos pés.',
    preco: 'R$ 189,90',
    parcelamento: '6x de R$ 31,65 sem juros',
    img: '/fotos/sandalias/sandalia10.jpeg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Design moderno com suporte ortopédico completo', 'Palmilha anatômica com correção postural', 'Material respirável para conforto térmico', 'Versátil para diferentes ocasiões', 'Disponível nos tamanhos 33 ao 40'],
    tags: ['Fashion', 'Ortopédica', 'Feminino', 'Estilo'],
  },
];

export const todosProdutos = [...oleos, ...purificadores, ...sandalias, ...sandaliasCarrossel, ...outrosProdutos];
