export const oleos = [
  {
    id: 1,
    slug: 'oleo-bergamota',
    nome: 'Óleo Essencial Bergamota',
    categoria: 'Óleo Essencial',
    descricao:
      'A Bergamota doTERRA é extraída da casca da fruta Citrus bergamia. Com aroma cítrico e floral único, é amplamente usada em aromaterapia para promover relaxamento, bem-estar emocional e equilíbrio mental.',
    preco: 'R$ 89,90',
    parcelamento: '3x de R$ 29,97 sem juros',
    img: '/fotos/oleos/aromas_naturais/bergamot.png',
    beneficios: [
      'Promove relaxamento e reduz a ansiedade',
      'Equilibra as emoções e eleva o humor',
      'Aroma cítrico e floral revigorante',
      'Ideal para difusores e uso tópico',
      'Purifica o ambiente e afasta energias negativas',
    ],
    tags: ['Calmante', 'Aromaterapia', 'doTERRA', 'Cítrico'],
  },
  {
    id: 2,
    slug: 'oleo-basil',
    nome: 'Óleo Essencial Basil',
    categoria: 'Óleo Essencial',
    descricao:
      'O Óleo Essencial de Basil (Manjericão) doTERRA é extraído das folhas da planta Ocimum basilicum. Com aroma herbáceo e levemente adocicado, é reconhecido por suas propriedades estimulantes, clarificantes e tonificantes.',
    preco: 'R$ 79,90',
    parcelamento: '3x de R$ 26,63 sem juros',
    img: '/fotos/oleos/aromas_naturais/brasil.png',
    beneficios: [
      'Estimula a concentração e a clareza mental',
      'Tonifica e revitaliza a mente e o corpo',
      'Ótimo para aliviar tensões musculares',
      'Purifica o ambiente com aroma herbáceo',
      'Apoia o sistema respiratório',
    ],
    tags: ['Estimulante', 'Herbal', 'doTERRA', 'Clareza Mental'],
  },
  {
    id: 3,
    slug: 'oleo-cardamomo',
    nome: 'Óleo Essencial Cardamomo',
    categoria: 'Óleo Essencial',
    descricao:
      'O Cardamomo doTERRA tem aroma quente, especiado e levemente adocicado. Extraído das sementes da planta Elettaria cardamomum, é amplamente utilizado para suporte digestivo, bem-estar emocional e revitalização.',
    preco: 'R$ 94,90',
    parcelamento: '3x de R$ 31,63 sem juros',
    img: '/fotos/oleos/aromas_naturais/cardamom.png',
    beneficios: [
      'Apoia a saúde digestiva e o metabolismo',
      'Aroma quente e especiado que aquece o ambiente',
      'Promove sensação de conforto e bem-estar',
      'Excelente para uso em difusor no inverno',
      'Estimula a vitalidade e a energia',
    ],
    tags: ['Digestivo', 'Especiado', 'doTERRA', 'Vitalizante'],
  },
  {
    id: 4,
    slug: 'oleo-cassia',
    nome: 'Óleo Essencial Cassia',
    categoria: 'Óleo Essencial',
    descricao:
      'A Cassia doTERRA tem um aroma quente, adocicado e especiado, semelhante à canela. Extraída da casca da Cinnamomum cassia, é conhecida por suas propriedades aquecedoras, estimulantes e de suporte ao sistema imunológico.',
    preco: 'R$ 84,90',
    parcelamento: '3x de R$ 28,30 sem juros',
    img: '/fotos/oleos/aromas_naturais/cassia.png',
    beneficios: [
      'Fortalece e apoia o sistema imunológico',
      'Aroma quente e reconfortante, semelhante à canela',
      'Estimula a circulação e a vitalidade',
      'Promove sensação de aquecimento no inverno',
      'Excelente para uso em difusor e culinária',
    ],
    tags: ['Imunidade', 'Aquecedor', 'doTERRA', 'Canela'],
  },
  {
    id: 5,
    slug: 'oleo-pimenta-preta',
    nome: 'Óleo Essencial Pimenta Preta',
    categoria: 'Óleo Essencial',
    descricao:
      'O Óleo Essencial de Pimenta Preta doTERRA é extraído das sementes imaturas da Piper nigrum. Com aroma picante, quente e levemente amadeirado, é reconhecido por suas propriedades estimulantes, antioxidantes e de suporte ao metabolismo.',
    preco: 'R$ 74,90',
    parcelamento: '3x de R$ 24,97 sem juros',
    img: '/fotos/oleos/aromas_naturais/black_pepper.png',
    beneficios: [
      'Estimula a circulação sanguínea',
      'Apoia o sistema digestivo e o metabolismo',
      'Rico em antioxidantes naturais',
      'Excelente para massagem terapêutica',
      'Aroma quente e revigorante',
    ],
    tags: ['Circulação', 'Antioxidante', 'doTERRA', 'Estimulante'],
  },
];

export const purificadores = [
  {
    id: 8,
    slug: 'purificador-azul-um-filtro',
    nome: 'Purificador de Água Natural Azul',
    categoria: 'Purificador de Água',
    descricao:
      'O Purificador Purific Azul é compacto e elegante, com um filtro de alta eficiência que remove impurezas, cloro e sedimentos. Ideal para famílias que buscam água limpa com design moderno e instalação simples.',
    preco: 'R$ 249,90',
    parcelamento: '10x de R$ 24,99 sem juros',
    img: '/fotos/purificador/purificador_agua_natural/purificador3.png',
    beneficios: [
      'Remove cloro, sedimentos e impurezas',
      'Design compacto e moderno na cor azul',
      'Instalação simples sem necessidade de técnico',
      'Filtro de longa duração e fácil reposição',
      'Certificado pela ANVISA',
    ],
    tags: ['Purificação', 'Compacto', 'Azul', 'Família'],
  },
  {
    id: 9,
    slug: 'purificador-preto-dois-filtros',
    nome: 'Purificador de Água Natural Preto',
    categoria: 'Purificador de Água',
    descricao:
      'O Purificador Purific Preto conta com dois filtros de purificação para máxima eficiência. Remove cloro, metais pesados, bactérias e impurezas em dupla etapa. Design sofisticado na cor preta, ideal para cozinhas modernas.',
    preco: 'R$ 319,90',
    parcelamento: '12x de R$ 26,66 sem juros',
    img: '/fotos/purificador/purificador_bebedouro/purificador4.png',
    beneficios: [
      'Dupla filtração para máxima pureza',
      'Remove cloro, metais pesados e bactérias',
      'Design sofisticado na cor preta',
      'Maior capacidade de filtragem',
      'Certificado pela ANVISA',
    ],
    tags: ['Duplo Filtro', 'Preto', 'Premium', 'Alta Eficiência'],
  },
  {
    id: 10,
    slug: 'purificador-branco-dois-filtros',
    nome: 'Purificador de Água Natural Branco',
    categoria: 'Purificador de Água',
    descricao:
      'O Purificador Purific Branco com dois filtros oferece purificação em dupla etapa com visual clean e sofisticado. Combina alta performance de filtragem com um design neutro que se adapta a qualquer ambiente.',
    preco: 'R$ 309,90',
    parcelamento: '12x de R$ 25,82 sem juros',
    img: '/fotos/purificador/purificador_agua_natural/purificador5.png',
    beneficios: [
      'Dupla filtração para água mais pura',
      'Design clean e neutro na cor branca',
      'Fácil manutenção e troca de filtros',
      'Remove impurezas, cloro e metais pesados',
      'Certificado pela ANVISA',
    ],
    tags: ['Duplo Filtro', 'Branco', 'Clean', 'Alta Eficiência'],
  },
  {
    id: 11,
    slug: 'purificador-preto-um-filtro',
    nome: 'Purificador Purific Preto Compacto',
    categoria: 'Purificador de Água',
    descricao:
      'Versão compacta do Purificador Purific na cor preta, com um filtro eficiente para purificação do dia a dia. Perfeito para espaços menores sem abrir mão da qualidade e do estilo.',
    preco: 'R$ 269,90',
    parcelamento: '10x de R$ 26,99 sem juros',
    img: '/fotos/purificador/purificador_agua_natural/purificador4.png',
    beneficios: [
      'Compacto e perfeito para espaços menores',
      'Remove cloro, sedimentos e impurezas',
      'Design elegante na cor preta',
      'Fácil instalação e manutenção',
      'Certificado pela ANVISA',
    ],
    tags: ['Compacto', 'Preto', 'Purificação', 'Prático'],
  },
  {
    id: 12,
    slug: 'purificador-branco-um-filtro',
    nome: 'Purificador Purific Branco Compacto',
    categoria: 'Purificador de Água',
    descricao:
      'O Purificador Purific Branco Compacto é a escolha ideal para quem busca praticidade e qualidade. Com design minimalista e filtro de alta eficiência, entrega água pura e saborosa no dia a dia.',
    preco: 'R$ 259,90',
    parcelamento: '10x de R$ 25,99 sem juros',
    img: '/fotos/purificador/purificador_agua_natural/purificador2.png',
    beneficios: [
      'Design minimalista e versátil',
      'Remove cloro, sedimentos e impurezas',
      'Ideal para cozinhas de qualquer tamanho',
      'Fácil instalação e manutenção',
      'Certificado pela ANVISA',
    ],
    tags: ['Compacto', 'Branco', 'Minimalista', 'Prático'],
  },
];

export const outrosProdutos = [
  {
    id: 6,
    slug: 'filtro-purific',
    nome: 'Filtro de Água "Purific"',
    categoria: 'Purificador de Água',
    descricao:
      'O Filtro Purific oferece purificação avançada em múltiplos estágios, eliminando impurezas, cloro, metais pesados e microrganismos. Design moderno e compacto, fácil instalação e baixa manutenção. Água limpa, pura e saudável para toda a família.',
    preco: 'R$ 349,90',
    parcelamento: '12x de R$ 29,16 sem juros',
    img: '/filtro de agua.jpg',
    beneficios: [
      'Purificação avançada em múltiplos estágios',
      'Remove cloro, metais pesados e microrganismos',
      'Design moderno e compacto',
      'Fácil instalação — sem necessidade de técnico',
      'Baixa manutenção e alta durabilidade',
      'Certificado pela ANVISA',
    ],
    tags: ['Saúde', 'Purificação', 'Família', 'Econômico'],
  },
  {
    id: 7,
    slug: 'kit-bem-estar-doterra',
    nome: 'Kit Bem-Estar doTERRA',
    categoria: 'Kit Essencial',
    descricao:
      'O Kit Bem-Estar doTERRA reúne os óleos essenciais mais populares da marca em um conjunto completo para transformar sua rotina. Ideal para iniciantes e para quem deseja ter sempre à mão as melhores soluções naturais para saúde, equilíbrio e bem-estar.',
    preco: 'R$ 389,90',
    parcelamento: '12x de R$ 32,49 sem juros',
    img: '/doTERRA_Essencial_Para_o_Lar.png',
    beneficios: [
      'Kit completo com os óleos essenciais mais populares',
      'Ideal para iniciantes em aromaterapia',
      'Soluções naturais para saúde e bem-estar diário',
      'Óleos 100% puros e certificados doTERRA',
      'Guia de uso incluído no kit',
      'Embalagem premium — ótima opção de presente',
    ],
    tags: ['Kit Completo', 'doTERRA', 'Presente', 'Bem-Estar'],
  },
];

export const todosProdutos = [...oleos, ...purificadores, ...outrosProdutos];
