const tamanhosSandalia = [33, 34, 35, 36, 37, 38, 39, 40];

export const oleos = [
  {
    id: 1,
    slug: 'oleo-bergamota',
    nome: 'Oleo Essencial Bergamota',
    categoria: 'Oleo Essencial',
    descricao: 'A Bergamota doTERRA e extraida da casca da fruta Citrus bergamia. Com aroma citrico e floral unico, e amplamente usada em aromaterapia para promover relaxamento, bem-estar emocional e equilibrio mental.',
    preco: 'R$ 89,90',
    parcelamento: '3x de R$ 29,97 sem juros',
    img: '/fotos/oleos/aromas_naturais/bergamot.png',
    beneficios: ['Promove relaxamento e reduz a ansiedade','Equilibra as emocoes e eleva o humor','Aroma citrico e floral revigorante','Ideal para difusores e uso topico','Purifica o ambiente'],
    tags: ['Calmante', 'Aromaterapia', 'doTERRA', 'Citrico'],
  },
  {
    id: 2,
    slug: 'oleo-basil',
    nome: 'Oleo Essencial Basil',
    categoria: 'Oleo Essencial',
    descricao: 'O Oleo Essencial de Basil (Manjericao) doTERRA e extraido das folhas da planta Ocimum basilicum. Com aroma herbaceo e levemente adocicado, e reconhecido por suas propriedades estimulantes e clarificantes.',
    preco: 'R$ 79,90',
    parcelamento: '3x de R$ 26,63 sem juros',
    img: '/fotos/oleos/aromas_naturais/brasil.png',
    beneficios: ['Estimula a concentracao e a clareza mental','Tonifica e revitaliza a mente e o corpo','Otimo para aliviar tensoes musculares','Purifica o ambiente com aroma herbaceo','Apoia o sistema respiratorio'],
    tags: ['Estimulante', 'Herbal', 'doTERRA', 'Clareza Mental'],
  },
  {
    id: 3,
    slug: 'oleo-cardamomo',
    nome: 'Oleo Essencial Cardamomo',
    categoria: 'Oleo Essencial',
    descricao: 'O Cardamomo doTERRA tem aroma quente, especiado e levemente adocicado. Extraido das sementes da planta Elettaria cardamomum, e amplamente utilizado para suporte digestivo e revitalizacao.',
    preco: 'R$ 94,90',
    parcelamento: '3x de R$ 31,63 sem juros',
    img: '/fotos/oleos/aromas_naturais/cardamom.png',
    beneficios: ['Apoia a saude digestiva e o metabolismo','Aroma quente e especiado','Promove sensacao de conforto e bem-estar','Excelente para uso em difusor no inverno','Estimula a vitalidade e a energia'],
    tags: ['Digestivo', 'Especiado', 'doTERRA', 'Vitalizante'],
  },
  {
    id: 4,
    slug: 'oleo-cassia',
    nome: 'Oleo Essencial Cassia',
    categoria: 'Oleo Essencial',
    descricao: 'A Cassia doTERRA tem um aroma quente, adocicado e especiado, semelhante a canela. Extraida da casca da Cinnamomum cassia, e conhecida por suas propriedades aquecedoras e de suporte ao sistema imunologico.',
    preco: 'R$ 84,90',
    parcelamento: '3x de R$ 28,30 sem juros',
    img: '/fotos/oleos/aromas_naturais/cassia.png',
    beneficios: ['Fortalece e apoia o sistema imunologico','Aroma quente e reconfortante, semelhante a canela','Estimula a circulacao e a vitalidade','Promove sensacao de aquecimento no inverno','Excelente para uso em difusor'],
    tags: ['Imunidade', 'Aquecedor', 'doTERRA', 'Canela'],
  },
  {
    id: 5,
    slug: 'oleo-pimenta-preta',
    nome: 'Oleo Essencial Pimenta Preta',
    categoria: 'Oleo Essencial',
    descricao: 'O Oleo Essencial de Pimenta Preta doTERRA e extraido das sementes imaturas da Piper nigrum. Com aroma picante, quente e levemente amadeirado, e reconhecido por suas propriedades estimulantes e antioxidantes.',
    preco: 'R$ 74,90',
    parcelamento: '3x de R$ 24,97 sem juros',
    img: '/fotos/oleos/aromas_naturais/black_pepper.png',
    beneficios: ['Estimula a circulacao sanguinea','Apoia o sistema digestivo e o metabolismo','Rico em antioxidantes naturais','Excelente para massagem terapeutica','Aroma quente e revigorante'],
    tags: ['Circulacao', 'Antioxidante', 'doTERRA', 'Estimulante'],
  },
];

export const purificadores = [
  {
    id: 8,
    slug: 'purificador-azul-um-filtro',
    nome: 'Purificador de Agua Natural Azul',
    categoria: 'Purificador de Agua',
    descricao: 'O Purificador Purific Azul e compacto e elegante, com um filtro de alta eficiencia que remove impurezas, cloro e sedimentos. Ideal para familias que buscam agua limpa com design moderno e instalacao simples.',
    preco: 'R$ 249,90',
    parcelamento: '10x de R$ 24,99 sem juros',
    img: '/fotos/purificador/purificador_agua_natural/purificador3.png',
    beneficios: ['Remove cloro, sedimentos e impurezas','Design compacto e moderno na cor azul','Instalacao simples sem necessidade de tecnico','Filtro de longa duracao e facil reposicao','Certificado pela ANVISA'],
    tags: ['Purificacao', 'Compacto', 'Azul', 'Familia'],
  },
  {
    id: 9,
    slug: 'purificador-preto-dois-filtros',
    nome: 'Purificador de Agua Natural Preto',
    categoria: 'Purificador de Agua',
    descricao: 'O Purificador Purific Preto conta com dois filtros de purificacao para maxima eficiencia. Remove cloro, metais pesados, bacterias e impurezas em dupla etapa. Design sofisticado na cor preta.',
    preco: 'R$ 319,90',
    parcelamento: '12x de R$ 26,66 sem juros',
    img: '/fotos/purificador/purificador_bebedouro/purificador4.png',
    beneficios: ['Dupla filtracao para maxima pureza','Remove cloro, metais pesados e bacterias','Design sofisticado na cor preta','Maior capacidade de filtragem','Certificado pela ANVISA'],
    tags: ['Duplo Filtro', 'Preto', 'Premium', 'Alta Eficiencia'],
  },
  {
    id: 10,
    slug: 'purificador-branco-dois-filtros',
    nome: 'Purificador de Agua Natural Branco',
    categoria: 'Purificador de Agua',
    descricao: 'O Purificador Purific Branco com dois filtros oferece purificacao em dupla etapa com visual clean e sofisticado. Combina alta performance de filtragem com um design neutro que se adapta a qualquer ambiente.',
    preco: 'R$ 309,90',
    parcelamento: '12x de R$ 25,82 sem juros',
    img: '/fotos/purificador/purificador_agua_natural/purificador5.png',
    beneficios: ['Dupla filtracao para agua mais pura','Design clean e neutro na cor branca','Facil manutencao e troca de filtros','Remove impurezas, cloro e metais pesados','Certificado pela ANVISA'],
    tags: ['Duplo Filtro', 'Branco', 'Clean', 'Alta Eficiencia'],
  },
  {
    id: 11,
    slug: 'purificador-preto-um-filtro',
    nome: 'Purificador Purific Preto Compacto',
    categoria: 'Purificador de Agua',
    descricao: 'Versao compacta do Purificador Purific na cor preta, com um filtro eficiente para purificacao do dia a dia. Perfeito para espacos menores sem abrir mao da qualidade e do estilo.',
    preco: 'R$ 269,90',
    parcelamento: '10x de R$ 26,99 sem juros',
    img: '/fotos/purificador/purificador_agua_natural/purificador4.png',
    beneficios: ['Compacto e perfeito para espacos menores','Remove cloro, sedimentos e impurezas','Design elegante na cor preta','Facil instalacao e manutencao','Certificado pela ANVISA'],
    tags: ['Compacto', 'Preto', 'Purificacao', 'Pratico'],
  },
  {
    id: 12,
    slug: 'purificador-branco-um-filtro',
    nome: 'Purificador Purific Branco Compacto',
    categoria: 'Purificador de Agua',
    descricao: 'O Purificador Purific Branco Compacto e a escolha ideal para quem busca praticidade e qualidade. Com design minimalista e filtro de alta eficiencia, entrega agua pura e saborosa no dia a dia.',
    preco: 'R$ 259,90',
    parcelamento: '10x de R$ 25,99 sem juros',
    img: '/fotos/purificador/purificador_agua_natural/purificador2.png',
    beneficios: ['Design minimalista e versatil','Remove cloro, sedimentos e impurezas','Ideal para cozinhas de qualquer tamanho','Facil instalacao e manutencao','Certificado pela ANVISA'],
    tags: ['Compacto', 'Branco', 'Minimalista', 'Pratico'],
  },
];

export const sandalias = [
  {
    id: 13,
    slug: 'sandalia-ortopedica-couro',
    nome: 'Sandalia Ortopedica Couro',
    categoria: 'Sandalia Ortopedica',
    descricao: 'Confeccionada em couro legitimo com palmilha anatomica para suporte total do arco plantar. Indicada para uso diario, corrige a postura e alivia dores nos pes, joelhos e coluna.',
    preco: 'R$ 189,90',
    parcelamento: '6x de R$ 31,65 sem juros',
    img: '/sandalia ce couro.jpg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Couro legitimo de alta durabilidade','Palmilha anatomica para suporte do arco plantar','Corrige a postura e alivia dores','Indicada para uso diario','Unissex - disponivel nos tamanhos 33 ao 40'],
    tags: ['Couro Legitimo', 'Arco Plantar', 'Unissex', 'Ortopedica'],
  },
  {
    id: 14,
    slug: 'sandalia-ortopedica-vazada',
    nome: 'Sandalia Ortopedica Vazada',
    categoria: 'Sandalia Ortopedica',
    descricao: 'Design vazado com solado ortopedico para maxima ventilacao e conforto. Leve e resistente, ideal para quem passa longos periodos em pe e busca frescor sem abrir mao do suporte postural.',
    preco: 'R$ 159,90',
    parcelamento: '6x de R$ 26,65 sem juros',
    img: '/sandaliavazada.jpeg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Design vazado para maxima ventilacao','Solado ortopedico com amortecimento','Extremamente leve e confortavel','Ideal para dias quentes e rotinas longas','Disponivel nos tamanhos 33 ao 40'],
    tags: ['Ventilada', 'Leve', 'Feminino', 'Ortopedica'],
  },
  {
    id: 15,
    slug: 'sandalia-ortopedica-premium',
    nome: 'Sandalia Ortopedica Premium',
    categoria: 'Sandalia Ortopedica',
    descricao: 'A linha Premium combina amortecimento extra com correcao postural avancada. Material nobre, acabamento impecavel e tecnologia ortopedica de alto nivel para quem exige o melhor para a saude dos pes.',
    preco: 'R$ 219,90',
    parcelamento: '6x de R$ 36,65 sem juros',
    img: '/sandalia ce couro.jpg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Amortecimento extra para maximo conforto','Correcao postural avancada','Material nobre com acabamento premium','Reduz dores nos pes, joelhos e coluna','Disponivel nos tamanhos 33 ao 40'],
    tags: ['Premium', 'Amortecimento', 'Postura', 'Ortopedica'],
  },
  {
    id: 16,
    slug: 'sandalia-magnetica-classic',
    nome: 'Sandalia Magnetica Classic',
    categoria: 'Sandalia Magnetica',
    descricao: 'Imaes terapeuticos estrategicamente posicionados para estimular a circulacao sanguinea e aliviar dores. A linha Classic e a introducao perfeita a tecnologia magnetica com estilo elegante e moderno.',
    preco: 'R$ 229,90',
    parcelamento: '6x de R$ 38,32 sem juros',
    img: '/sandalia2.jpg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Imaes terapeuticos para estimular a circulacao','Alivia dores e reduz inflamacoes','Estilo elegante para uso no dia a dia','Promove equilibrio energetico','Disponivel nos tamanhos 33 ao 40'],
    tags: ['Circulacao', 'Terapeutica', 'Unissex', 'Magnetica'],
  },
  {
    id: 17,
    slug: 'sandalia-magnetica-bio',
    nome: 'Sandalia Magnetica Bio',
    categoria: 'Sandalia Magnetica',
    descricao: 'Combina tecnologia magnetica com materiais bioativos para bem-estar total. Os materiais bioativos potencializam a acao dos imaes, promovendo recuperacao muscular, equilibrio e vitalidade ao longo do dia.',
    preco: 'R$ 249,90',
    parcelamento: '6x de R$ 41,65 sem juros',
    img: '/sandalia ce couro.jpg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Materiais bioativos que potencializam os imaes','Promove recuperacao muscular acelerada','Estimula o equilibrio energetico','Alta tecnologia para bem-estar total','Disponivel nos tamanhos 33 ao 40'],
    tags: ['Bioativo', 'Alta Tecnologia', 'Feminino', 'Magnetica'],
  },
  {
    id: 18,
    slug: 'sandalia-magnetica-sport',
    nome: 'Sandalia Magnetica Sport',
    categoria: 'Sandalia Magnetica',
    descricao: 'Para quem tem rotina ativa. Magnetos de alta intensidade combinados com solado antiderrapante e estrutura reforcada para suportar os desafios do dia a dia com conforto e seguranca.',
    preco: 'R$ 269,90',
    parcelamento: '6x de R$ 44,98 sem juros',
    img: '/sandalia2.jpg',
    tamanhos: tamanhosSandalia,
    beneficios: ['Magnetos de alta intensidade para maximo efeito','Solado antiderrapante para maior seguranca','Estrutura reforcada para rotinas ativas','Ideal para quem pratica atividades fisicas','Disponivel nos tamanhos 33 ao 40'],
    tags: ['Esportivo', 'Antiderrapante', 'Unissex', 'Magnetica'],
  },
];

export const outrosProdutos = [
  {
    id: 6,
    slug: 'filtro-purific',
    nome: 'Filtro de Agua Purific',
    categoria: 'Purificador de Agua',
    descricao: 'O Filtro Purific oferece purificacao avancada em multiplos estagios, eliminando impurezas, cloro, metais pesados e microrganismos. Design moderno e compacto, facil instalacao e baixa manutencao.',
    preco: 'R$ 349,90',
    parcelamento: '12x de R$ 29,16 sem juros',
    img: '/filtro de agua.jpg',
    beneficios: ['Purificacao avancada em multiplos estagios','Remove cloro, metais pesados e microrganismos','Design moderno e compacto','Facil instalacao sem necessidade de tecnico','Baixa manutencao e alta durabilidade','Certificado pela ANVISA'],
    tags: ['Saude', 'Purificacao', 'Familia', 'Economico'],
  },
  {
    id: 7,
    slug: 'kit-bem-estar-doterra',
    nome: 'Kit Bem-Estar doTERRA',
    categoria: 'Kit Essencial',
    descricao: 'O Kit Bem-Estar doTERRA reune os oleos essenciais mais populares da marca em um conjunto completo para transformar sua rotina. Ideal para iniciantes e para quem deseja ter sempre a mao as melhores solucoes naturais.',
    preco: 'R$ 389,90',
    parcelamento: '12x de R$ 32,49 sem juros',
    img: '/doTERRA_Essencial_Para_o_Lar.png',
    beneficios: ['Kit completo com os oleos essenciais mais populares','Ideal para iniciantes em aromaterapia','Solucoes naturais para saude e bem-estar diario','Oleos 100% puros e certificados doTERRA','Guia de uso incluido no kit','Embalagem premium - otima opcao de presente'],
    tags: ['Kit Completo', 'doTERRA', 'Presente', 'Bem-Estar'],
  },
];

export const todosProdutos = [...oleos, ...purificadores, ...sandalias, ...outrosProdutos];