
export const oleos = [
  {
    id: 1,
    slug: 'oleo-bergamota',
    nome: 'Bergamot - Óleo Essencial',
    categoria: 'Óleo Essencial',
    subtitulo: 'Aroma cítrico e refrescante, ideal para equilíbrio emocional e bem-estar.',
    descricao: 'A Bergamota doTERRA é extraída da casca da fruta Citrus bergamia. Com aroma cítrico e floral único, é amplamente usada em aromaterapia para promover relaxamento, bem-estar emocional e equilíbrio mental.',
    preco: 'R$ 310,00',
    parcelamento: '3x de R$ 103,33 sem juros',
    tamanho: '15 ml',
    img: '/fotos/oleos/aromas_naturais/bergamot.png',
    beneficios: ['Reduz ansiedade e estresse', 'Promove sensação de calma e alegria', 'Purifica e limpa a pele', 'Ideal para aromaterapia e difusores', 'Equilibra as emoções e eleva o humor'],
    tags: ['Calmante', 'Aromaterapia', 'doTERRA', 'Cítrico'],
    comoUsar: [
      { icon: '💨', titulo: 'Difusor', desc: '3–4 gotas no difusor para ambientar qualquer espaço.' },
      { icon: '🖐️', titulo: 'Tópico', desc: 'Dilua com óleo carreador e aplique na pele.' },
      { icon: '🛁', titulo: 'Banho', desc: 'Adicione gotas no banho para relaxamento profundo.' },
      { icon: '🌿', titulo: 'Inalação', desc: 'Respire diretamente do frasco para alívio imediato.' },
    ],
  },
  {
    id: 2,
    slug: 'oleo-pimenta-preta',
    nome: 'Black Pepper - Óleo Essencial',
    categoria: 'Óleo Essencial',
    subtitulo: 'Estimulante e aquecedor, perfeito para circulação e desconforto muscular.',
    descricao: 'O Óleo Essencial de Pimenta Preta doTERRA é extraído das sementes imaturas da Piper nigrum. Com aroma picante, quente e levemente amadeirado, é reconhecido por suas propriedades estimulantes e antioxidantes.',
    preco: 'R$ 250,00',
    parcelamento: '3x de R$ 83,33 sem juros',
    tamanho: '5 ml',
    img: '/fotos/oleos/aromas_naturais/black_pepper.png',
    beneficios: ['Estimula a circulação sanguínea', 'Alivia tensão e desconforto muscular', 'Apoia a digestão saudável', 'Rico em antioxidantes naturais', 'Aroma quente e revigorante'],
    tags: ['Circulação', 'Antioxidante', 'doTERRA', 'Estimulante'],
    comoUsar: [
      { icon: '💨', titulo: 'Difusor', desc: '2–3 gotas para um ambiente aquecedor e energizante.' },
      { icon: '🖐️', titulo: 'Massagem', desc: 'Dilua e massageie em áreas de tensão muscular.' },
      { icon: '🍽️', titulo: 'Culinário', desc: '1 gota em receitas para sabor e digestão.' },
      { icon: '🌿', titulo: 'Inalação', desc: 'Inalação direta para foco e energia.' },
    ],
  },
  {
    id: 3,
    slug: 'oleo-basil',
    nome: 'Basil - Óleo Essencial',
    categoria: 'Óleo Essencial',
    subtitulo: 'Herbal e refrescante, excelente para clareza mental e relaxamento.',
    descricao: 'O Óleo Essencial de Manjericão doTERRA é extraído das folhas da planta Ocimum basilicum. Com aroma herbal, fresco e levemente adocicado, é amplamente utilizado para clareza mental, relaxamento e suporte digestivo.',
    preco: 'R$ 307,00',
    parcelamento: '3x de R$ 102,33 sem juros',
    tamanho: '15 ml',
    img: '/fotos/oleos/aromas_naturais/brasil.png',
    beneficios: ['Promove clareza mental e foco', 'Reduz fadiga e estresse mental', 'Apoia a digestão saudável', 'Aroma herbal fresco e revitalizante', 'Ideal para difusor e uso tópico diluído'],
    tags: ['Clareza Mental', 'Herbal', 'doTERRA', 'Relaxante'],
    comoUsar: [
      { icon: '💨', titulo: 'Difusor', desc: '3–4 gotas no difusor para clareza e foco.' },
      { icon: '🧘', titulo: 'Meditação', desc: 'Use durante práticas de meditação e yoga.' },
      { icon: '🖐️', titulo: 'Tópico', desc: 'Dilua e aplique nas têmporas para foco mental.' },
      { icon: '🌿', titulo: 'Inalação', desc: 'Inalação direta para alívio imediato de fadiga.' },
    ],
  },
  {
    id: 4,
    slug: 'oleo-cardamomo',
    nome: 'Cardamomo - Óleo Essencial',
    categoria: 'Óleo Essencial',
    subtitulo: 'Doce e especiado, excelente para digestão e respiração saudável.',
    descricao: 'O Cardamomo doTERRA tem aroma quente, especiado e levemente adocicado. Extraído das sementes da planta Elettaria cardamomum, é amplamente utilizado para suporte digestivo e revitalização.',
    preco: 'R$ 272,00',
    parcelamento: '3x de R$ 90,67 sem juros',
    tamanho: '5 ml',
    img: '/fotos/oleos/aromas_naturais/cardamom.png',
    beneficios: ['Apoia a saúde digestiva e o metabolismo', 'Promove respiração limpa e fácil', 'Aroma doce, quente e especiado', 'Propriedades anti-inflamatórias naturais', 'Estimula a vitalidade e a energia'],
    tags: ['Digestivo', 'Especiado', 'doTERRA', 'Vitalizante'],
    comoUsar: [
      { icon: '💨', titulo: 'Difusor', desc: '3 gotas para um aroma quente e acolhedor.' },
      { icon: '🍽️', titulo: 'Culinário', desc: '1 gota em chás, cafés e sobremesas.' },
      { icon: '🖐️', titulo: 'Tópico', desc: 'Aplique diluído no abdômen para suporte digestivo.' },
      { icon: '🌿', titulo: 'Inalação', desc: 'Inalação direta para clareza respiratória.' },
    ],
  },
  {
    id: 5,
    slug: 'oleo-cassia',
    nome: 'Cassia - Óleo Essencial',
    categoria: 'Óleo Essencial',
    subtitulo: 'Similar à canela, com propriedades quentes e estimulantes do bem-estar.',
    descricao: 'A Cassia doTERRA tem um aroma quente, adocicado e especiado, semelhante à canela. Extraída da casca da Cinnamomum cassia, é conhecida por suas propriedades aquecedoras e de suporte ao sistema imunológico.',
    preco: 'R$ 200,00',
    parcelamento: '3x de R$ 66,67 sem juros',
    tamanho: '15 ml',
    img: '/fotos/oleos/aromas_naturais/cassia.png',
    beneficios: ['Fortalece e apoia o sistema imunológico', 'Aroma quente e reconfortante, semelhante à canela', 'Estimula a circulação e a vitalidade', 'Promove sensação de aquecimento', 'Excelente para uso em difusor'],
    tags: ['Imunidade', 'Aquecedor', 'doTERRA', 'Canela'],
    comoUsar: [
      { icon: '💨', titulo: 'Difusor', desc: '2 gotas para um ambiente aconchegante no inverno.' },
      { icon: '🍽️', titulo: 'Culinário', desc: '1 gota em receitas que pedem canela.' },
      { icon: '🖐️', titulo: 'Tópico', desc: 'Dilua bastante antes de aplicar na pele.' },
      { icon: '🛁', titulo: 'Banho', desc: '2 gotas no banho para aquecimento corporal.' },
    ],
  },
  {
    id: 24,
    slug: 'oleo-adaptiv',
    nome: 'Adaptiv Mix Calmante',
    categoria: 'Mix de Óleos Essenciais',
    subtitulo: 'Mix calmante para suporte ao bem-estar emocional e redução do estresse.',
    descricao: 'O Adaptiv doTERRA é um mix de óleos essenciais formulado para trazer calma e conforto em momentos de estresse e ansiedade. Combina óleos com propriedades calmantes para equilibrar as emoções e promover tranquilidade.',
    preco: 'R$ 378,00',
    parcelamento: '3x de R$ 126,00 sem juros',
    tamanho: '15 ml',
    img: '/fotos/oleos/mix_oleo_essencial/adaptiv.png',
    beneficios: ['Promove sensação de calma e tranquilidade', 'Reduz o estresse e a ansiedade', 'Apoia o bem-estar emocional', 'Aroma equilibrante e relaxante', 'Ideal para momentos de tensão e pressão'],
    tags: ['Calmante', 'Estresse', 'doTERRA', 'Mix Essencial'],
    comoUsar: [
      { icon: '💨', titulo: 'Difusor', desc: '4 gotas no difusor para criar um ambiente de calma.' },
      { icon: '🖐️', titulo: 'Tópico', desc: 'Dilua e aplique no pescoço e pulsos para alívio.' },
      { icon: '🧘', titulo: 'Meditação', desc: 'Use durante práticas de meditação e respiração.' },
      { icon: '🌿', titulo: 'Inalação', desc: 'Respire diretamente para alívio imediato do estresse.' },
    ],
  },
  {
    id: 25,
    slug: 'oleo-adaptiv-touch',
    nome: 'Adaptiv Touch Mix Calmante',
    categoria: 'Mix de Óleos Essenciais',
    subtitulo: 'Versão roll-on do Mix Calmante, prática para aplicação tópica a qualquer hora.',
    descricao: 'O Adaptiv Touch doTERRA traz a fórmula calmante do Adaptiv® em formato roll-on prático. Pré-diluído em óleo carreador, facilita a aplicação tópica direta nos pulsos, pescoço e têmporas sempre que precisar.',
    preco: 'R$ 200,00',
    parcelamento: '3x de R$ 66,67 sem juros',
    tamanho: '10 ml',
    img: '/fotos/oleos/mix_oleo_essencial/adaptiv_touch.png',
    beneficios: ['Formato roll-on para aplicação prática e rápida', 'Pré-diluído pronto para uso tópico', 'Promove calma e bem-estar emocional', 'Ideal para levar na bolsa no dia a dia', 'Alivia o estresse onde e quando precisar'],
    tags: ['Calmante', 'Roll-on', 'doTERRA', 'Prático'],
    comoUsar: [
      { icon: '🖐️', titulo: 'Pulsos', desc: 'Aplique nos pulsos e esfregue suavemente.' },
      { icon: '🌿', titulo: 'Pescoço', desc: 'Passe no pescoço para relaxamento rápido.' },
      { icon: '😌', titulo: 'Têmporas', desc: 'Aplique nas têmporas para alívio de tensão.' },
      { icon: '👃', titulo: 'Inalação', desc: 'Após aplicar, respire fundo para potencializar o efeito.' },
    ],
  },
  {
    id: 26,
    slug: 'oleo-air-x',
    nome: 'Air-X Mix de Óleos Essenciais',
    categoria: 'Mix de Óleos Essenciais',
    subtitulo: 'Mix respiratório que apoia a saúde das vias aéreas e o conforto respiratório.',
    descricao: 'O Air-X® doTERRA é um mix de óleos essenciais desenvolvido para oferecer suporte às vias respiratórias. Combina óleos com propriedades que facilitam a respiração limpa, confortável e revigorante.',
    preco: 'R$ 232,00',
    parcelamento: '3x de R$ 77,33 sem juros',
    tamanho: '15 ml',
    img: '/fotos/oleos/mix_oleo_essencial/air_x.png',
    beneficios: ['Apoia a saúde das vias respiratórias', 'Promove respiração limpa e confortável', 'Alivia desconfortos respiratórios sazonais', 'Aroma fresco e revigorante', 'Ideal para difusor durante estações de alergias'],
    tags: ['Respiratório', 'Vias Aéreas', 'doTERRA', 'Mix Essencial'],
    comoUsar: [
      { icon: '💨', titulo: 'Difusor', desc: '3–4 gotas no difusor para purificar o ambiente.' },
      { icon: '🖐️', titulo: 'Tópico', desc: 'Dilua e aplique no peito e costas para suporte respiratório.' },
      { icon: '🌿', titulo: 'Inalação', desc: 'Inalação direta para alívio respiratório imediato.' },
      { icon: '🛁', titulo: 'Banho a Vapor', desc: 'Adicione gotas na água quente do banho e respire o vapor.' },
    ],
  },
];

export const purificadores = [
  {
    id: 8,
    slug: 'refil-purific-camadas-6l',
    nome: 'Refil Purific Camadas 6 Litros',
    categoria: 'Refil / Elemento Filtrante',
    subtitulo: 'Elemento filtrante com 7 camadas de purificação para máxima eficiência.',
    descricao: 'O Refil Purific Camadas 6 Litros é um elemento filtrante com 7 camadas de purificação que remove cloro, sedimentos, metais pesados e contaminantes. Ideal para reposição em purificadores Purific de 6 litros.',
    preco: 'R$ 658,30',
    precoPix: 'R$ 625.39 no PIX (-5%)',
    parcelamento: '8x de R$ 82,28',
    img: '/fotos/purificador/purificador_agua_natural/purificador3.png',
    tags: ['Refil', '7 Camadas', 'Purific', '6 Litros'],
    specs: [
      { label: 'Tipo', valor: 'Elemento Filtrante (Refil)' },
      { label: 'Capacidade', valor: '6 Litros' },
      { label: 'Camadas de filtração', valor: '7 camadas' },
      { label: 'Compatibilidade', valor: 'Purificadores Purific 6L' },
      { label: 'Garantia', valor: '12 meses' },
    ],
    diferenciais: [
      { icon: '💧', titulo: '7 Camadas', desc: 'Sete estágios de purificação para água mais pura e segura.' },
      { icon: '🔄', titulo: 'Fácil Troca', desc: 'Substituição simples, sem ferramentas ou técnico.' },
      { icon: '💰', titulo: 'Econômico', desc: 'Custo por litro muito menor que água engarrafada.' },
      { icon: '🌱', titulo: 'Sustentável', desc: 'Reduce o uso de garrafas plásticas descartáveis.' },
    ],
  },
  {
    id: 9,
    slug: 'refil-purific-low-fluor-10l',
    nome: 'Refil Purific Low Flúor 10L Bebedouro',
    categoria: 'Refil / Elemento Filtrante',
    subtitulo: 'Refil redutor de flúor para bebedouros com capacidade de 10 litros.',
    descricao: 'O Refil Purific Low Flúor 10L é desenvolvido para bebedouros e reduz significativamente o flúor e outros contaminantes presentes na água. Ideal para quem busca maior controle sobre os níveis de flúor no consumo diário.',
    preco: 'R$ 960,00',
    precoPix: 'R$ 912,00 no PIX (-5%)',
    parcelamento: '8x de R$ 120,00',
    img: '/fotos/purificador/purificador_bebedouro/purificador4.png',
    tags: ['Refil', 'Redutor de Flúor', 'Bebedouro', '10 Litros'],
    specs: [
      { label: 'Tipo', valor: 'Elemento Filtrante (Refil)' },
      { label: 'Capacidade', valor: '10 Litros' },
      { label: 'Redução', valor: 'Flúor' },
      { label: 'Compatibilidade', valor: 'Bebedouros Purific 10L' },
      { label: 'Garantia', valor: '12 meses' },
    ],
    diferenciais: [
      { icon: '🚫', titulo: 'Reduz Flúor', desc: 'Redução eficiente dos níveis de flúor na água.' },
      { icon: '🔄', titulo: 'Fácil Troca', desc: 'Substituição prática no seu bebedouro.' },
      { icon: '💧', titulo: 'Água Saudável', desc: 'Melhora a qualidade e o sabor da água.' },
      { icon: '🌱', titulo: 'Sustentável', desc: 'Menos plástico descartável no seu dia a dia.' },
    ],
  },
  {
    id: 10,
    slug: 'purificador-low-fluor-10l-bebedouro',
    nome: 'Purificador Purific Low Flúor 10L Bebedouro',
    categoria: 'Purificador de Água',
    subtitulo: 'Redutor de flúor especialmente indicado para gestantes e bebês.',
    descricao: 'O Purificador Purific Low Flúor 10L para Bebedouro é indicado especialmente para gestantes, bebês e quem necessita controlar a ingestão de flúor. Com capacidade de 10 litros, garante água segura e saudável para toda a família.',
    preco: 'R$ 960,00',
    precoPix: 'R$ 912,00 no PIX (-5%)',
    parcelamento: '8x de R$ 120,00',
    img: '/fotos/purificador/purificador_agua_natural/purificador5.png',
    tags: ['Low Flúor', 'Gestantes', 'Bebedouro', '10 Litros'],
    specs: [
      { label: 'Tipo', valor: 'Purificador para Bebedouro' },
      { label: 'Capacidade', valor: '10 Litros' },
      { label: 'Redução', valor: 'Flúor' },
      { label: 'Indicação', valor: 'Gestantes e Bebês' },
      { label: 'Garantia', valor: '12 meses' },
    ],
    diferenciais: [
      { icon: '👶', titulo: 'Para Gestantes', desc: 'Especialmente indicado para gestantes e bebês.' },
      { icon: '🚫', titulo: 'Reduz Flúor', desc: 'Controle seguro dos níveis de flúor na água.' },
      { icon: '💧', titulo: '10 Litros', desc: 'Grande capacidade para o consumo familiar.' },
      { icon: '🌱', titulo: 'Saúde em 1º lugar', desc: 'Água mais pura e segura para os primeiros anos de vida.' },
    ],
  },
  {
    id: 11,
    slug: 'purificador-defense-6l-bebedouro',
    nome: 'Purificador Purific Defense 6L Bebedouro',
    categoria: 'Purificador de Água',
    subtitulo: 'Proteção avançada contra agrotóxicos e metais pesados.',
    descricao: 'O Purificador Purific Defense 6L é desenvolvido com tecnologia avançada para reduzir agrotóxicos e metais pesados presentes na água. Ideal para regiões agrícolas ou onde a qualidade da água é mais comprometida.',
    preco: 'R$ 658,30',
    precoPix: 'R$ 625,38 no PIX (-5%)',
    parcelamento: '8x de R$ 82,28',
    img: '/fotos/purificador/purificador_agua_natural/purificador4.png',
    tags: ['Defense', 'Agrotóxicos', 'Metais Pesados', 'Bebedouro'],
    specs: [
      { label: 'Tipo', valor: 'Purificador para Bebedouro' },
      { label: 'Capacidade', valor: '6 Litros' },
      { label: 'Redução', valor: 'Agrotóxicos e Metais Pesados' },
      { label: 'Tecnologia', valor: 'Defense' },
      { label: 'Garantia', valor: '12 meses' },
    ],
    diferenciais: [
      { icon: '🛡️', titulo: 'Defense', desc: 'Tecnologia avançada contra agrotóxicos e contaminantes.' },
      { icon: '⚗️', titulo: 'Metais Pesados', desc: 'Remove chumbo, mercúrio e outros metais nocivos.' },
      { icon: '🌾', titulo: 'Agrotóxicos', desc: 'Redução eficiente de resíduos de pesticidas.' },
      { icon: '💧', titulo: 'Água Segura', desc: 'Proteção completa para você e sua família.' },
    ],
  },
  {
    id: 12,
    slug: 'purificador-alcalinum-6l-bancada',
    nome: 'Purificador Purific Alcalinum 6L Bancada',
    categoria: 'Purificador de Água',
    subtitulo: 'Água alcalina com pH 8,9 para melhor hidratação e bem-estar.',
    descricao: 'O Purificador Purific Alcalinum 6L de Bancada transforma a água filtrada em água alcalina com pH 8,9. A água alcalina é reconhecida por promover melhor hidratação celular, equilíbrio do pH do organismo e bem-estar geral.',
    preco: 'R$ 598,00',
    precoPix: 'R$ 568,10 no PIX (-5%)',
    parcelamento: '8x de R$ 74,75',
    img: '/fotos/purificador/purificador_agua_natural/purificador2.png',
    tags: ['Alcalino', 'pH 8,9', 'Bancada', '6 Litros'],
    specs: [
      { label: 'Tipo', valor: 'Purificador de Bancada' },
      { label: 'Capacidade', valor: '6 Litros' },
      { label: 'pH da Água', valor: '8,9' },
      { label: 'Tecnologia', valor: 'Alcalinização' },
      { label: 'Garantia', valor: '12 meses' },
    ],
    diferenciais: [
      { icon: '⚗️', titulo: 'pH 8,9', desc: 'Água alcalina com pH ideal para o equilíbrio do organismo.' },
      { icon: '💧', titulo: 'Hidratação Superior', desc: 'Moléculas menores para melhor absorção celular.' },
      { icon: '🏠', titulo: 'Bancada', desc: 'Prático, sem instalação hidráulica necessária.' },
      { icon: '✨', titulo: 'Bem-Estar', desc: 'Contribui para o equilíbrio do pH e vitalidade diária.' },
    ],
  },
  {
    id: 40,
    slug: 'purificador-alcalinum-10l-bancada',
    nome: 'Purificador Purific Alcalinum 10L Bancada',
    categoria: 'Purificador de Água',
    subtitulo: 'Maior capacidade alcalina para famílias que exigem mais saúde e qualidade.',
    descricao: 'O Purificador Purific Alcalinum 10L de Bancada oferece água alcalina com pH 8,9 em maior capacidade, ideal para famílias. Sem necessidade de instalação hidráulica, entrega água purificada e alcalinizada diretamente na sua bancada.',
    preco: 'R$ 960,00',
    precoPix: 'R$ 912,00 no PIX (-5%)',
    parcelamento: '8x de R$ 120,00',
    img: '/fotos/purificador/purificador_agua_natural/purific6.png',
    tags: ['Alcalino', 'pH 8,9', 'Bancada', '10 Litros'],
    specs: [
      { label: 'Tipo', valor: 'Purificador de Bancada' },
      { label: 'Capacidade', valor: '10 Litros' },
      { label: 'pH da Água', valor: '8,9' },
      { label: 'Tecnologia', valor: 'Alcalinização' },
      { label: 'Garantia', valor: '12 meses' },
    ],
    diferenciais: [
      { icon: '⚗️', titulo: 'pH 8,9', desc: 'Água alcalina com pH ideal para o equilíbrio do organismo.' },
      { icon: '👨‍👩‍👧‍👦', titulo: 'Para Famílias', desc: '10 litros de capacidade para o consumo de todos.' },
      { icon: '🏠', titulo: 'Bancada', desc: 'Prático, sem necessidade de instalação hidráulica.' },
      { icon: '✨', titulo: 'Bem-Estar', desc: 'Contribui para o equilíbrio do pH e vitalidade diária.' },
    ],
  },
];

export const sandalias = [
  {
    id: 13,
    slug: 'sandalia-aurora',
    nome: 'Sandália Aurora',
    categoria: 'Sandália Ortopédica e Magnética',
    descricao: 'Plataforma elevada com palmilha anatômica e imãs terapêuticos para máximo suporte postural e estimulação da circulação. Design moderno com fivela dourada, ideal para uso diário com muito estilo.',
    preco: 'R$ 399,00',
    parcelamento: '3x de R$ 133,00 sem juros',
    img: '/fotos/sandalias/aurora.png',
    tamanhos: [33, 34, 35, 36, 37, 38, 39, 40],
    beneficios: ['Palmilha anatômica com suporte total do arco plantar', 'Imãs terapêuticos para estimular a circulação', 'Plataforma que alivia pressão no calcanhar', 'Fivela dourada de acabamento premium', 'Disponível nos tamanhos 33 ao 40'],
    tags: ['Plataforma', 'Magnética', 'Ortopédica', 'Fivela Dourada'],
  },
  {
    id: 14,
    slug: 'sandalia-helena',
    nome: 'Sandália Helena',
    categoria: 'Sandália Ortopédica e Magnética',
    descricao: 'Salto médio com estrutura ortopédica e tecnologia magnética. Tiras firmes com fivela dourada garantem estabilidade e elegância. Disponível em duas cores: preta e vermelha.',
    preco: 'R$ 374,00',
    parcelamento: '3x de R$ 124,66 sem juros',
    img: '/fotos/sandalias/helena_preta.png',
    tamanhos: [33, 35, 36, 37, 38, 39],
    cores: [
      { nome: 'Preta', img: '/fotos/sandalias/helena_preta.png', tamanhos: [33, 35, 36, 37, 38, 39] },
      { nome: 'Vermelha', img: '/fotos/sandalias/helena_vermelha.png', tamanhos: [33, 34, 35, 36, 37, 38, 39] },
    ],
    beneficios: ['Salto médio para postura correta', 'Imãs terapêuticos integrados à palmilha', 'Tiras com fivela dourada para firmeza e estilo', 'Alivia dores nos pés, joelhos e coluna', 'Disponível em preto e vermelho'],
    tags: ['Salto Médio', 'Magnética', 'Ortopédica', 'Duas Cores'],
  },
  {
    id: 15,
    slug: 'sandalia-mere',
    nome: 'Sandália Mere',
    categoria: 'Sandália Ortopédica e Magnética',
    descricao: 'Mule com salto baixo em couro bicolor (marrom e bege) com fivela elegante. Palmilha anatômica com imãs terapêuticos para conforto prolongado no dia a dia.',
    preco: 'R$ 624,15',
    parcelamento: '5x de R$ 124,83 sem juros',
    img: '/fotos/sandalias/mere.png',
    tamanhos: [33, 34, 35, 36, 37, 38, 39, 40],
    beneficios: ['Couro bicolor marrom e bege de alta qualidade', 'Salto baixo para conforto e segurança', 'Palmilha anatômica com imãs terapêuticos', 'Estilo refinado para múltiplas ocasiões', 'Disponível nos tamanhos 33 ao 40'],
    tags: ['Mule', 'Couro Bicolor', 'Magnética', 'Ortopédica'],
  },
  {
    id: 16,
    slug: 'sandalia-erica',
    nome: 'Sandália Érica',
    categoria: 'Sandália Ortopédica e Magnética',
    descricao: 'Anabela com tiras cruzadas em tom nude/bege, combinando leveza com suporte postural. Os imãs terapêuticos na palmilha estimulam a circulação enquanto a plataforma distribui o peso uniformemente.',
    preco: 'R$ 377,00',
    parcelamento: '3x de R$ 125,66 sem juros',
    img: '/fotos/sandalias/erica.png',
    tamanhos: [34, 35, 36, 37, 38, 39, 40],
    beneficios: ['Anabela que distribui o peso uniformemente', 'Tiras cruzadas para maior estabilidade', 'Imãs terapêuticos para estimular a circulação', 'Tom nude versátil para qualquer look', 'Disponível nos tamanhos 34 ao 40'],
    tags: ['Anabela', 'Tiras Cruzadas', 'Magnética', 'Ortopédica'],
  },
  {
    id: 17,
    slug: 'sandalia-dafne',
    nome: 'Sandália Dafne',
    categoria: 'Sandália Ortopédica e Magnética',
    descricao: 'Tênis-sandália branco com cadarço e solado de borracha. Combina o visual casual do sneaker com a tecnologia ortopédica e magnética para máximo conforto em rotinas ativas.',
    preco: 'R$ 419,88',
    parcelamento: '3x de R$ 139,96 sem juros',
    img: '/fotos/sandalias/dafne.png',
    tamanhos: [36, 37, 38, 39],
    beneficios: ['Visual casual estilo sneaker', 'Solado de borracha antiderrapante', 'Palmilha ortopédica com imãs terapêuticos', 'Cadarço para ajuste personalizado', 'Disponível nos tamanhos 36 ao 39'],
    tags: ['Tênis', 'Casual', 'Magnética', 'Ortopédica'],
  },
];

export const outrosProdutos = [
  {
    id: 6,
    slug: 'filtro-purific',
    nome: 'Filtro de Agua Purific',
    categoria: 'Purificador de Agua',
    descricao: 'O Filtro Purific oferece purificacao avancada em multiplos estagios, eliminando impurezas, cloro, metais pesados e microrganismos. Design moderno e compacto, facil instalacao e baixa manutencao.',
    preco: 'R$ 349,90',
    parcelamento: '12x de R$ 29,16 sem juros',
    img: '/fotos/purificador/filtro_de_agua.jpg',
    beneficios: ['Purificacao avancada em multiplos estagios', 'Remove cloro, metais pesados e microrganismos', 'Design moderno e compacto', 'Facil instalacao sem necessidade de tecnico', 'Baixa manutencao e alta durabilidade', 'Certificado pela ANVISA'],
    tags: ['Saude', 'Purificacao', 'Familia', 'Economico'],
  },
  {
    id: 7,
    slug: 'kit-bem-estar-doterra',
    nome: 'Kit Bem-Estar doTERRA',
    categoria: 'Kit Essencial',
    descricao: 'O Kit Bem-Estar doTERRA reune os oleos essenciais mais populares da marca em um conjunto completo para transformar sua rotina. Ideal para iniciantes e para quem deseja ter sempre a mao as melhores solucoes naturais.',
    preco: 'R$ 389,90',
    parcelamento: '12x de R$ 32,49 sem juros',
    img: '/fotos/oleos/doTERRA_Essencial_Para_o_Lar.png',
    beneficios: ['Kit completo com os oleos essenciais mais populares', 'Ideal para iniciantes em aromaterapia', 'Solucoes naturais para saude e bem-estar diario', 'Oleos 100% puros e certificados doTERRA', 'Guia de uso incluido no kit', 'Embalagem premium - otima opcao de presente'],
    tags: ['Kit Completo', 'doTERRA', 'Presente', 'Bem-Estar'],
  },
];

export const sandaliasCarrossel = sandalias;

export const todosProdutos = [...oleos, ...purificadores, ...sandalias, ...outrosProdutos];
